# PHP CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
#
version: 2

jobs:
  "php-7.1":
    docker:
      - image: aimeos/ci-php:7.1
    steps:
      - checkout
      - restore_cache:
          keys:
            - php71-{{ checksum "composer.json" }}
      - run: composer update -n --prefer-dist
      - save_cache:
          key: php71-{{ checksum "composer.json" }}
          paths: [./vendor]
      - run: ./vendor/bin/phpunit

  "php-7.2":
    docker:
      - image: aimeos/ci-php:7.2
    steps:
      - checkout
      - restore_cache:
          keys:
            - php72-{{ checksum "composer.json" }}
      - run: composer update -n --prefer-dist
      - save_cache:
          key: php72-{{ checksum "composer.json" }}
          paths: [./vendor]
      - run: ./vendor/bin/phpunit

  "php-7.3":
    docker:
      - image: aimeos/ci-php:7.3
    steps:
      - checkout
      - restore_cache:
          keys:
            - php73-{{ checksum "composer.json" }}
      - run: composer update -n --prefer-dist
      - save_cache:
          key: php73-{{ checksum "composer.json" }}
          paths: [./vendor]
      - run: ./vendor/bin/phpunit

  "php-7.4":
    docker:
      - image: aimeos/ci-php:7.4
    steps:
      - checkout
      - restore_cache:
          keys:
            - php74-{{ checksum "composer.json" }}
      - run: composer update -n --prefer-dist
      - save_cache:
          key: php74-{{ checksum "composer.json" }}
          paths: [./vendor]
      - run: ./vendor/bin/phpunit

  "php-8.0":
    docker:
      - image: aimeos/ci-php:8.0
    steps:
      - checkout
      - restore_cache:
          keys:
            - php80-{{ checksum "composer.json" }}
      - run: composer update -n --prefer-dist
      - save_cache:
          key: php80-{{ checksum "composer.json" }}
          paths: [./vendor]
      - run: ./vendor/bin/phpunit --coverage-clover coverage.xml
      - run: ./vendor/bin/php-coveralls -vvv -o coverage.json -x coverage.xml

  "php-8.1":
    docker:
      - image: aimeos/ci-php:8.1
    steps:
      - checkout
      - restore_cache:
          keys:
            - php80-{{ checksum "composer.json" }}
      - run: composer update -n --prefer-dist
      - save_cache:
          key: php80-{{ checksum "composer.json" }}
          paths: [./vendor]
      - run: ./vendor/bin/phpunit

workflows:
  version: 2
  unittest:
    jobs:
      - "php-7.1"
      - "php-7.2"
      - "php-7.3"
      - "php-7.4"
      - "php-8.0"
      - "php-8.1"
